name: Pull request checks and tests

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
        # Skip running workflow if only FE/docs files have changed.
        - 'docs'
        - 'djproducts/templates/**'

jobs:

  checks:
    name: Run Django checks

    runs-on: ubuntu-latest

    env:
      # Cross-step environment variables; note that these
      # variables cannot interpolate string values from
      # the services, as that must occur at step-level.
      DJANGO_SETTINGS_MODULE: djproducts.settings.test
      DATABASE_URL: postgres://test:test@postgres:5432/test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.in-project true

      - name: Install virtual environment and dependencies
        run: |
          cd api
          poetry install

      # NB: The following steps have repeated environment variables because interpolating
      # string values from the services can only occur at the step-level & not globally.

      - name: Check for missing migrations
        run: |
          cd api
          source .venv/bin/activate
          python manage.py makemigrations --dry-run --check --verbosity=3 --settings=djproducts.settings.sqlite

      - name: Run Django system checks
        run: |
          cd api
          source .venv/bin/activate
          python manage.py check --fail-level WARNING --settings=djproducts.settings.sqlite